#!/usr/bin/env python
import sys, os

'''

Merge output root files
Specify the directory where your output files are stored, i.e. /home/scratch/kmpark/zjets/
Only thing you'll need to change is line #12 pstored value

'''

pstored = "/home/scratch/kyungminpark/2018/Z_CR1_DY/"

version="%s"%os.environ["CMSSW_VERSION"]
pmerged=pstored+"results_merged/" 

if pmerged not in os.listdir(pstored):
    os.system("mkdir -p "+pmerged)
    print("'results_merged' has been created.")

print(pstored, pmerged, os.listdir(pstored))
dir_list = [x for x in os.listdir(pstored) if (os.path.isdir(pstored+x) and x != "results_merged")]
print(dir_list)

failed_list = []
for d in dir_list:
    print(pstored+d)
    root_list = [x for x in os.listdir(pstored+d) if (x.endswith(".root"))]
    file_names = ""
    for x in root_list:
        file_names += " %s/%s"%(pstored+d,x)
    if len(root_list) == 0:
        failed_list.append(d)
    else:
        print("hadd -f %s.root %s"%(pmerged+d,file_names))
        os.system("hadd -f %s.root %s"%(pmerged+d,file_names))

if len(failed_list) > 0:
    print(" ** What failed:    ", failed_list)
